name: silk_demo_00
description: Silk Demo


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  silk_annotation: 

  flutter_riverpod:
  riverpod_annotation:
  freezed:
  freezed_annotation:

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  riverpod_generator:

flutter:

  uses-material-design: true